// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetOperatorInput struct {
	Name string `json:"name"`
}

type Operator struct {
	Name      string   `json:"name"`
	Class     string   `json:"class"`
	Rarity    int      `json:"rarity"`
	Available []string `json:"available"`
}
